# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

services:
  spicedb:
    networks: !override
      - certs-base-net

  spicedb-migrate:
    networks: !override
      - certs-base-net

  spicedb-db:
    networks: !override
      - certs-base-net

  auth-db:
    networks: !override
      - certs-base-net

  auth-redis:
    networks: !override
      - certs-base-net

  auth:
    networks: !override
      - certs-base-net

  domains-db:
    networks: !override
      - certs-base-net

  domains-redis:
    networks: !override
      - certs-base-net

  domains:
    networks: !override
      - certs-base-net

  clients-db:
    networks: !override
      - certs-base-net

  clients-redis:
    networks: !override
      - certs-base-net

  clients:
    networks: !override
      - certs-base-net

  channels-redis:
    networks: !override
      - certs-base-net

  channels-db:
    networks: !override
      - certs-base-net

  channels:
    networks: !override
      - certs-base-net

  users-db:
    networks: !override
      - certs-base-net

  users:
    networks: !override
      - certs-base-net

  groups-db:
    networks: !override
      - certs-base-net

  groups:
    networks: !override
      - certs-base-net

  jaeger:
    networks: !override
      - certs-base-net

  mqtt-adapter:
    networks: !override
      - certs-base-net

  http-adapter:
    networks: !override
      - certs-base-net

  coap-adapter:
    networks: !override
      - certs-base-net

  ws-adapter:
    networks: !override
      - certs-base-net

  rabbitmq:
    networks: !override
      - certs-base-net

  nats:
    networks: !override
      - certs-base-net

  nginx:
    container_name: certs-nginx
    volumes:
      - ../../docker/nginx/nginx-${AUTH-key}.conf:/etc/nginx/nginx.conf.template
      - ../../docker/nginx/entrypoint.sh:/docker-entrypoint.d/entrypoint.sh
      - type: bind
        source: ${SMQ_NGINX_SERVER_CERT:-../../docker/ssl/certs/certs-server.crt}
        target: /etc/ssl/certs/certs-server.crt
      - type: bind
        source: ${SMQ_NGINX_SERVER_KEY:-../../docker/ssl/certs/certs-server.key}
        target: /etc/ssl/private/certs-server.key
      - type: bind
        source: ${SMQ_NGINX_SERVER_CLIENT_CA:-../../docker/ssl/certs/ca.crt}
        target: /etc/ssl/certs/ca.crt
      - type: bind
        source: ${SMQ_NGINX_SERVER_DHPARAM:-../../docker/ssl/dhparam.pem}
        target: /etc/ssl/certs/dhparam.pem
    networks: !override
      - certs-base-net
    env_file: !override
      - ./.env
      - ../../docker/.env