// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify
// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

package mocks

import (
	"context"

	"github.com/absmach/certs"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

// NewMockCertsServiceClient creates a new instance of MockCertsServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCertsServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCertsServiceClient {
	mock := &MockCertsServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCertsServiceClient is an autogenerated mock type for the CertsServiceClient type
type MockCertsServiceClient struct {
	mock.Mock
}

type MockCertsServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCertsServiceClient) EXPECT() *MockCertsServiceClient_Expecter {
	return &MockCertsServiceClient_Expecter{mock: &_m.Mock}
}

// GetCA provides a mock function for the type MockCertsServiceClient
func (_mock *MockCertsServiceClient) GetCA(ctx context.Context, in *certs.GetCAReq, opts ...grpc.CallOption) (*certs.Cert, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetCA")
	}

	var r0 *certs.Cert
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *certs.GetCAReq, ...grpc.CallOption) (*certs.Cert, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *certs.GetCAReq, ...grpc.CallOption) *certs.Cert); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certs.Cert)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *certs.GetCAReq, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCertsServiceClient_GetCA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCA'
type MockCertsServiceClient_GetCA_Call struct {
	*mock.Call
}

// GetCA is a helper method to define mock.On call
//   - ctx context.Context
//   - in *certs.GetCAReq
//   - opts ...grpc.CallOption
func (_e *MockCertsServiceClient_Expecter) GetCA(ctx interface{}, in interface{}, opts ...interface{}) *MockCertsServiceClient_GetCA_Call {
	return &MockCertsServiceClient_GetCA_Call{Call: _e.mock.On("GetCA",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCertsServiceClient_GetCA_Call) Run(run func(ctx context.Context, in *certs.GetCAReq, opts ...grpc.CallOption)) *MockCertsServiceClient_GetCA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *certs.GetCAReq
		if args[1] != nil {
			arg1 = args[1].(*certs.GetCAReq)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCertsServiceClient_GetCA_Call) Return(cert *certs.Cert, err error) *MockCertsServiceClient_GetCA_Call {
	_c.Call.Return(cert, err)
	return _c
}

func (_c *MockCertsServiceClient_GetCA_Call) RunAndReturn(run func(ctx context.Context, in *certs.GetCAReq, opts ...grpc.CallOption) (*certs.Cert, error)) *MockCertsServiceClient_GetCA_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntityID provides a mock function for the type MockCertsServiceClient
func (_mock *MockCertsServiceClient) GetEntityID(ctx context.Context, in *certs.EntityReq, opts ...grpc.CallOption) (*certs.EntityRes, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetEntityID")
	}

	var r0 *certs.EntityRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *certs.EntityReq, ...grpc.CallOption) (*certs.EntityRes, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *certs.EntityReq, ...grpc.CallOption) *certs.EntityRes); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certs.EntityRes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *certs.EntityReq, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCertsServiceClient_GetEntityID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntityID'
type MockCertsServiceClient_GetEntityID_Call struct {
	*mock.Call
}

// GetEntityID is a helper method to define mock.On call
//   - ctx context.Context
//   - in *certs.EntityReq
//   - opts ...grpc.CallOption
func (_e *MockCertsServiceClient_Expecter) GetEntityID(ctx interface{}, in interface{}, opts ...interface{}) *MockCertsServiceClient_GetEntityID_Call {
	return &MockCertsServiceClient_GetEntityID_Call{Call: _e.mock.On("GetEntityID",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCertsServiceClient_GetEntityID_Call) Run(run func(ctx context.Context, in *certs.EntityReq, opts ...grpc.CallOption)) *MockCertsServiceClient_GetEntityID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *certs.EntityReq
		if args[1] != nil {
			arg1 = args[1].(*certs.EntityReq)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCertsServiceClient_GetEntityID_Call) Return(entityRes *certs.EntityRes, err error) *MockCertsServiceClient_GetEntityID_Call {
	_c.Call.Return(entityRes, err)
	return _c
}

func (_c *MockCertsServiceClient_GetEntityID_Call) RunAndReturn(run func(ctx context.Context, in *certs.EntityReq, opts ...grpc.CallOption) (*certs.EntityRes, error)) *MockCertsServiceClient_GetEntityID_Call {
	_c.Call.Return(run)
	return _c
}

// IssueCert provides a mock function for the type MockCertsServiceClient
func (_mock *MockCertsServiceClient) IssueCert(ctx context.Context, in *certs.IssueCertReq, opts ...grpc.CallOption) (*certs.IssueCertRes, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for IssueCert")
	}

	var r0 *certs.IssueCertRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *certs.IssueCertReq, ...grpc.CallOption) (*certs.IssueCertRes, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *certs.IssueCertReq, ...grpc.CallOption) *certs.IssueCertRes); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certs.IssueCertRes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *certs.IssueCertReq, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCertsServiceClient_IssueCert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueCert'
type MockCertsServiceClient_IssueCert_Call struct {
	*mock.Call
}

// IssueCert is a helper method to define mock.On call
//   - ctx context.Context
//   - in *certs.IssueCertReq
//   - opts ...grpc.CallOption
func (_e *MockCertsServiceClient_Expecter) IssueCert(ctx interface{}, in interface{}, opts ...interface{}) *MockCertsServiceClient_IssueCert_Call {
	return &MockCertsServiceClient_IssueCert_Call{Call: _e.mock.On("IssueCert",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCertsServiceClient_IssueCert_Call) Run(run func(ctx context.Context, in *certs.IssueCertReq, opts ...grpc.CallOption)) *MockCertsServiceClient_IssueCert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *certs.IssueCertReq
		if args[1] != nil {
			arg1 = args[1].(*certs.IssueCertReq)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCertsServiceClient_IssueCert_Call) Return(issueCertRes *certs.IssueCertRes, err error) *MockCertsServiceClient_IssueCert_Call {
	_c.Call.Return(issueCertRes, err)
	return _c
}

func (_c *MockCertsServiceClient_IssueCert_Call) RunAndReturn(run func(ctx context.Context, in *certs.IssueCertReq, opts ...grpc.CallOption) (*certs.IssueCertRes, error)) *MockCertsServiceClient_IssueCert_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveCert provides a mock function for the type MockCertsServiceClient
func (_mock *MockCertsServiceClient) RetrieveCert(ctx context.Context, in *certs.RetrieveCertReq, opts ...grpc.CallOption) (*certs.CertificateBundle, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RetrieveCert")
	}

	var r0 *certs.CertificateBundle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *certs.RetrieveCertReq, ...grpc.CallOption) (*certs.CertificateBundle, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *certs.RetrieveCertReq, ...grpc.CallOption) *certs.CertificateBundle); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certs.CertificateBundle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *certs.RetrieveCertReq, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCertsServiceClient_RetrieveCert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveCert'
type MockCertsServiceClient_RetrieveCert_Call struct {
	*mock.Call
}

// RetrieveCert is a helper method to define mock.On call
//   - ctx context.Context
//   - in *certs.RetrieveCertReq
//   - opts ...grpc.CallOption
func (_e *MockCertsServiceClient_Expecter) RetrieveCert(ctx interface{}, in interface{}, opts ...interface{}) *MockCertsServiceClient_RetrieveCert_Call {
	return &MockCertsServiceClient_RetrieveCert_Call{Call: _e.mock.On("RetrieveCert",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCertsServiceClient_RetrieveCert_Call) Run(run func(ctx context.Context, in *certs.RetrieveCertReq, opts ...grpc.CallOption)) *MockCertsServiceClient_RetrieveCert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *certs.RetrieveCertReq
		if args[1] != nil {
			arg1 = args[1].(*certs.RetrieveCertReq)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCertsServiceClient_RetrieveCert_Call) Return(certificateBundle *certs.CertificateBundle, err error) *MockCertsServiceClient_RetrieveCert_Call {
	_c.Call.Return(certificateBundle, err)
	return _c
}

func (_c *MockCertsServiceClient_RetrieveCert_Call) RunAndReturn(run func(ctx context.Context, in *certs.RetrieveCertReq, opts ...grpc.CallOption) (*certs.CertificateBundle, error)) *MockCertsServiceClient_RetrieveCert_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveCertDownloadToken provides a mock function for the type MockCertsServiceClient
func (_mock *MockCertsServiceClient) RetrieveCertDownloadToken(ctx context.Context, in *certs.RetrieveCertDownloadTokenReq, opts ...grpc.CallOption) (*certs.RetrieveCertDownloadTokenRes, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RetrieveCertDownloadToken")
	}

	var r0 *certs.RetrieveCertDownloadTokenRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *certs.RetrieveCertDownloadTokenReq, ...grpc.CallOption) (*certs.RetrieveCertDownloadTokenRes, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *certs.RetrieveCertDownloadTokenReq, ...grpc.CallOption) *certs.RetrieveCertDownloadTokenRes); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certs.RetrieveCertDownloadTokenRes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *certs.RetrieveCertDownloadTokenReq, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCertsServiceClient_RetrieveCertDownloadToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveCertDownloadToken'
type MockCertsServiceClient_RetrieveCertDownloadToken_Call struct {
	*mock.Call
}

// RetrieveCertDownloadToken is a helper method to define mock.On call
//   - ctx context.Context
//   - in *certs.RetrieveCertDownloadTokenReq
//   - opts ...grpc.CallOption
func (_e *MockCertsServiceClient_Expecter) RetrieveCertDownloadToken(ctx interface{}, in interface{}, opts ...interface{}) *MockCertsServiceClient_RetrieveCertDownloadToken_Call {
	return &MockCertsServiceClient_RetrieveCertDownloadToken_Call{Call: _e.mock.On("RetrieveCertDownloadToken",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCertsServiceClient_RetrieveCertDownloadToken_Call) Run(run func(ctx context.Context, in *certs.RetrieveCertDownloadTokenReq, opts ...grpc.CallOption)) *MockCertsServiceClient_RetrieveCertDownloadToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *certs.RetrieveCertDownloadTokenReq
		if args[1] != nil {
			arg1 = args[1].(*certs.RetrieveCertDownloadTokenReq)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCertsServiceClient_RetrieveCertDownloadToken_Call) Return(retrieveCertDownloadTokenRes *certs.RetrieveCertDownloadTokenRes, err error) *MockCertsServiceClient_RetrieveCertDownloadToken_Call {
	_c.Call.Return(retrieveCertDownloadTokenRes, err)
	return _c
}

func (_c *MockCertsServiceClient_RetrieveCertDownloadToken_Call) RunAndReturn(run func(ctx context.Context, in *certs.RetrieveCertDownloadTokenReq, opts ...grpc.CallOption) (*certs.RetrieveCertDownloadTokenRes, error)) *MockCertsServiceClient_RetrieveCertDownloadToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeCerts provides a mock function for the type MockCertsServiceClient
func (_mock *MockCertsServiceClient) RevokeCerts(ctx context.Context, in *certs.RevokeReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RevokeCerts")
	}

	var r0 *emptypb.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *certs.RevokeReq, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *certs.RevokeReq, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *certs.RevokeReq, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCertsServiceClient_RevokeCerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeCerts'
type MockCertsServiceClient_RevokeCerts_Call struct {
	*mock.Call
}

// RevokeCerts is a helper method to define mock.On call
//   - ctx context.Context
//   - in *certs.RevokeReq
//   - opts ...grpc.CallOption
func (_e *MockCertsServiceClient_Expecter) RevokeCerts(ctx interface{}, in interface{}, opts ...interface{}) *MockCertsServiceClient_RevokeCerts_Call {
	return &MockCertsServiceClient_RevokeCerts_Call{Call: _e.mock.On("RevokeCerts",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCertsServiceClient_RevokeCerts_Call) Run(run func(ctx context.Context, in *certs.RevokeReq, opts ...grpc.CallOption)) *MockCertsServiceClient_RevokeCerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *certs.RevokeReq
		if args[1] != nil {
			arg1 = args[1].(*certs.RevokeReq)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCertsServiceClient_RevokeCerts_Call) Return(empty *emptypb.Empty, err error) *MockCertsServiceClient_RevokeCerts_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *MockCertsServiceClient_RevokeCerts_Call) RunAndReturn(run func(ctx context.Context, in *certs.RevokeReq, opts ...grpc.CallOption) (*emptypb.Empty, error)) *MockCertsServiceClient_RevokeCerts_Call {
	_c.Call.Return(run)
	return _c
}
