// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	certs "github.com/absmach/certs"

	emptypb "google.golang.org/protobuf/types/known/emptypb"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MockCertsServiceClient is an autogenerated mock type for the CertsServiceClient type
type MockCertsServiceClient struct {
	mock.Mock
}

type MockCertsServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCertsServiceClient) EXPECT() *MockCertsServiceClient_Expecter {
	return &MockCertsServiceClient_Expecter{mock: &_m.Mock}
}

// GetEntityID provides a mock function with given fields: ctx, in, opts
func (_m *MockCertsServiceClient) GetEntityID(ctx context.Context, in *certs.EntityReq, opts ...grpc.CallOption) (*certs.EntityRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetEntityID")
	}

	var r0 *certs.EntityRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *certs.EntityReq, ...grpc.CallOption) (*certs.EntityRes, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *certs.EntityReq, ...grpc.CallOption) *certs.EntityRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certs.EntityRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *certs.EntityReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertsServiceClient_GetEntityID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntityID'
type MockCertsServiceClient_GetEntityID_Call struct {
	*mock.Call
}

// GetEntityID is a helper method to define mock.On call
//   - ctx context.Context
//   - in *certs.EntityReq
//   - opts ...grpc.CallOption
func (_e *MockCertsServiceClient_Expecter) GetEntityID(ctx interface{}, in interface{}, opts ...interface{}) *MockCertsServiceClient_GetEntityID_Call {
	return &MockCertsServiceClient_GetEntityID_Call{Call: _e.mock.On("GetEntityID",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCertsServiceClient_GetEntityID_Call) Run(run func(ctx context.Context, in *certs.EntityReq, opts ...grpc.CallOption)) *MockCertsServiceClient_GetEntityID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*certs.EntityReq), variadicArgs...)
	})
	return _c
}

func (_c *MockCertsServiceClient_GetEntityID_Call) Return(_a0 *certs.EntityRes, _a1 error) *MockCertsServiceClient_GetEntityID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertsServiceClient_GetEntityID_Call) RunAndReturn(run func(context.Context, *certs.EntityReq, ...grpc.CallOption) (*certs.EntityRes, error)) *MockCertsServiceClient_GetEntityID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeCerts provides a mock function with given fields: ctx, in, opts
func (_m *MockCertsServiceClient) RevokeCerts(ctx context.Context, in *certs.RevokeReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RevokeCerts")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *certs.RevokeReq, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *certs.RevokeReq, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *certs.RevokeReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertsServiceClient_RevokeCerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeCerts'
type MockCertsServiceClient_RevokeCerts_Call struct {
	*mock.Call
}

// RevokeCerts is a helper method to define mock.On call
//   - ctx context.Context
//   - in *certs.RevokeReq
//   - opts ...grpc.CallOption
func (_e *MockCertsServiceClient_Expecter) RevokeCerts(ctx interface{}, in interface{}, opts ...interface{}) *MockCertsServiceClient_RevokeCerts_Call {
	return &MockCertsServiceClient_RevokeCerts_Call{Call: _e.mock.On("RevokeCerts",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCertsServiceClient_RevokeCerts_Call) Run(run func(ctx context.Context, in *certs.RevokeReq, opts ...grpc.CallOption)) *MockCertsServiceClient_RevokeCerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*certs.RevokeReq), variadicArgs...)
	})
	return _c
}

func (_c *MockCertsServiceClient_RevokeCerts_Call) Return(_a0 *emptypb.Empty, _a1 error) *MockCertsServiceClient_RevokeCerts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertsServiceClient_RevokeCerts_Call) RunAndReturn(run func(context.Context, *certs.RevokeReq, ...grpc.CallOption) (*emptypb.Empty, error)) *MockCertsServiceClient_RevokeCerts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCertsServiceClient creates a new instance of MockCertsServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCertsServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCertsServiceClient {
	mock := &MockCertsServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
